### ISSUE TITLE
Create and link to a chat channel?

### ISSUE THREAD

**Issue by hrj** [fossasia/sciencehack.in#15]
I haven't attended a hackathon before so I don't know if it makes sense for participants to chat before the event.

If it makes sense, perhaps have an IRC / Gitter / Matrix room?

**Comment by hiteshd** [comment]
Making now on gitter

**Comment by mariobehling** [comment]
Please join us here https://fossasia.slack.com/messages/sciencehackday-in/

Get an invite here: http://fossasia-slack.herokuapp.com/

@wavicles Please add a this to the website.

**Comment by wavicles** [comment]
Adding now

**Comment by wavicles** [comment]
Link added
