### ISSUE TITLE
Adjust Site Style to FOSSASIA, fix small design issues and adjust colors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/sciencehack.in#35]
* [ ] Fix the menu bar - currently it disappears when scrolling
* [ ] Re-use the FOSSASIA style top menu bar and include the science hack logo (in white) on the top left
* [ ] Take out "Register Here" on top bar
* [ ] Change top background to red style
* [ ] Change link color to red across page
* [ ] Separate css from pages

![screenshot from 2017-01-03 22-03-15](https://cloud.githubusercontent.com/assets/1583873/21623055/ebc12856-d200-11e6-8a0b-86c9c4104a85.png)

**Comment by alejoheredia** [comment]
@mariobehling I want to work on this

**Comment by alejoheredia** [comment]
Do you mean something like the top menu bar in https://fossasia.org/?

**Comment by alejoheredia** [comment]
With "Change link color to red across page" do you mean the yellow one?

**Comment by mariobehling** [comment]
> link color

Change all links to red color similar to fossasia.org (except on menu).

**Comment by alejoheredia** [comment]
@mariobehling Instead of blue, the color must be red, right?

**Comment by alejoheredia** [comment]
And the background color of the menu must be always red, right?

**Comment by mariobehling** [comment]
I think you misunderstand. Please compare to http://pslab.fossasia.org for example. Style should be similar across fossasia pages. Thanks.

**Comment by alejoheredia** [comment]
The icon should be this?
![screen shot 2017-01-03 at 6 33 20 pm](https://cloud.githubusercontent.com/assets/15079370/21627046/2d01fdae-d1e3-11e6-9d3f-fe4e43eb5ee6.png)

**Comment by alejoheredia** [comment]
This is my progress 
![screen shot 2017-01-03 at 6 40 40 pm](https://cloud.githubusercontent.com/assets/15079370/21627199/2d01acb8-d1e4-11e6-9fb1-a54bc3a3a877.png)

**Comment by alejoheredia** [comment]
@mariobehling The navbar should be always red?

**Comment by alejoheredia** [comment]
![screen shot 2017-01-04 at 10 53 56 am](https://cloud.githubusercontent.com/assets/15079370/21648475/278d97b4-d26c-11e6-896b-131bf2433d3f.png)
![screen shot 2017-01-04 at 10 53 50 am](https://cloud.githubusercontent.com/assets/15079370/21648474/278c89a0-d26c-11e6-99c4-c53e938106e7.png)

I think that it would be better if it turns white when you scroll the page to the white section, like above

**Comment by jigyasa-grover** [comment]
Yes, @Heredroky pls provide a demo link ?

**Comment by Heredroky** [comment]
@jig08 With which link does the image have to join with?

**Comment by alejoheredia** [comment]
@jig08 Check the preview: https://heredroky.github.io/sciencehack.in/index.html
